cue: Use SILENCE instead of ZERO.
Although cdrdao(1) says they are interchangable, this does not seem to
actually be the case.

    ERROR: 1.toc:8: Mixing of FILE/AUDIOFILE/SILENCE and DATAFILE/ZERO
    statements not allowed.